### ISSUE TITLE
About GazeHub

### ISSUE THREAD

**Issue by TeresaKumo** [yihuacheng/Gaze-Net#1]
Hi @yihuacheng, thank you for your great job! But when I want to look for **data processing codes** in **http://phi-ai.org/GazeHub/**, I found I can't reach the pages. Is there any problem?

**Comment by TeresaKumo** [comment]
Now the web looks good

**Comment by YuhaoCheng** [comment]
Hi @yihuacheng , thank you for the great work, however, I find the  http://phi-ai.org/GazeHub/ is broken again. Would you mind fixing it again? Thanks for your time.
